# Generated by Django 2.1.7 on 2019-07-13 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testkit', '0001_initial'),
        ('users', '0002_auto_20190713_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='test_kits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_kits', to='testkit.TestKit'),
        ),
    ]
