# Generated by Django 2.1.7 on 2019-07-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_test_kits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='test_kits',
        ),
    ]
