# Generated by Django 2.1.7 on 2019-07-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testkit', '0005_remove_testkit_user'),
        ('users', '0004_remove_profile_test_kits'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='testkits',
            field=models.ManyToManyField(to='testkit.TestKit'),
        ),
    ]
