# Generated by Django 2.1.7 on 2019-07-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_testkits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='testkits',
            field=models.ManyToManyField(related_name='testkits', to='testkit.TestKit'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
