# Generated by Django 2.1.7 on 2019-07-13 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testkit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testkit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_kits', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
