# Generated by Django 2.1.7 on 2019-07-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testkit', '0002_testkit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='testkit',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
