# Generated by Django 2.1.7 on 2019-07-14 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testkit', '0003_testkit_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='testkit',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
