# Generated by Django 2.1.7 on 2019-07-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testkit', '0004_testkit_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testkit',
            name='user',
        ),
    ]
